name: Deploy to Firebase Hosting on production
'on':
  push:
    branches:
      - production
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      # - name: yarn version stable
      #   run: yarn set version stable
      - name: Install npm modules
        run: yarn install
      - name: Build app
        run: yarn generate
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCALAMATSURI_2024_WEB }}
          channelId: live
          projectId: scalamatsuri-2024-web
